name: Survival
version: 2.3.1
author: PAS123, BlueIronGirl and Abgie
api-version: 1.13

main: net.mmm.survival.Survival

commands:
  complain:
  economy:
    aliases: [eco]
  gamemode:
    aliases: [gm]
  home:
  info:
  money:
  navi:
    aliases: [navigation]
  pay:
  save:
  sethome:
  setspawn:
  spawn:
  tame:
  vote:
  zone:
  licence:

depend: [dynmap, WorldEdit, BungeeGroupManager, Votifier, WorldGuard]