name: Survival
version: 2.0.63
author: PAS123, BlueIronGirl and Abgie
api-version: 1.13

main: net.mmm.survival.Survival

commands:
  economy:
    aliases: [eco]
  gamemode:
    aliases: [gm]
  home:
  info:
  money:
  navi:
    aliases: [navigation]
  pay:
  sethome:
  setspawn:
  spawn:
  tame:
  vote:
  zone: